def get_columns() -> list: 
    return [
        "Country",
        "Year",
        "ISO Code",
        "Population",
        "GDP",
        "Cement CO2",
        "Cement CO2 per Capita",
        "CO2",
        "CO2 Growth abs",
        "CO2 Growth prct",
        "CO2 including LUC",
        "CO2 including LUC Growth abs",
        "CO2 including LUC Growth prct",
        "CO2 including LUC per Capita",
        "CO2 including LUC per GDP",
        "CO2 including LUC per Unit Energy",
        "CO2 per Capita",
        "CO2 per GDP",
        "CO2 per Unit Energy",
        "Coal CO2",
        "Coal CO2 per Capita",
        "Consumption CO2",
        "Consumption CO2 per Capita",
        "Consumption CO2 per GDP",
        "Cumulative Cement CO2",
        "Cumulative CO2",
        "Cumulative CO2 including LUC",
        "Cumulative Coal CO2",
        "Cumulative Flaring CO2",
        "Cumulative Gas CO2",
        "Cumulative LUC CO2",
        "Cumulative Oil CO2",
        "Cumulative Other CO2",
        "Energy per Capita",
        "Energy per GDP",
        "Flaring CO2",
        "Flaring CO2 per Capita",
        "Gas CO2",
        "Gas CO2 per Capita",
        "GHG excluding LUCF per Capita",
        "GHG per Capita",
        "Land Use Change CO2",
        "Land Use Change CO2 per Capita",
        "Methane",
        "Methane per Capita",
        "Nitrous Oxide",
        "Nitrous Oxide per Capita",
        "Oil CO2",
        "Oil CO2 per Capita",
        "Other CO2 per Capita",
        "Other Industry CO2",
        "Primary Energy Consumption",
        "Share Global Cement CO2",
        "Share Global CO2",
        "Share Global CO2 including LUC",
        "Share Global Coal CO2",
        "Share Global Cumulative Cement CO2",
        "Share Global Cumulative CO2",
        "Share Global Cumulative CO2 including LUC",
        "Share Global Cumulative Coal CO2",
        "Share Global Cumulative Flaring CO2",
        "Share Global Cumulative Gas CO2",
        "Share Global Cumulative LUC CO2",
        "Share Global Cumulative Oil CO2",
        "Share Global Cumulative Other CO2",
        "Share Global Flaring CO2",
        "Share Global Gas CO2",
        "Share Global LUC CO2",
        "Share Global Oil CO2",
        "Share Global Other CO2",
        "Share of Temperature Change from GHG",
        "Temperature Change from CH4",
        "Temperature Change from CO2",
        "Temperature Change from GHG",
        "Temperature Change from N2O",
        "Total GHG",
        "Total GHG excluding LUCF",
        "Trade CO2",
        "Trade CO2 Share"
    ]